### ISSUE TITLE
How to edit rich presence ?

### ISSUE THREAD

**Issue by RoadToMoonlight** [Pigpog/vlc-discord-rpc#11]
Hi guys,
I've try some things for edit rich presence but it's do something and it's always "Play VLC Media Player" and i want to see "Play" and the movie i watch ^^

I'm good in Programming Language but actually i don't find how to edit that :/
It's the AppID ?

**Comment by Pigpog** [comment]
The name of the rich presence is not controlled by any script. The idea of changing the "Playing" status for every new thing you watch is ridiculously complex in practice. To change the "playing" status, the owner of the app id (me in this case) would have to change the name of the application for every user of that application.
I believe that the current setup is as good as it can get at this time with the node modules i used.
