### ISSUE TITLE
Script doesn't adjust it's time remaining according to the playback speed.

### ISSUE THREAD

**Issue by DominykasPetke** [Pigpog/vlc-discord-rpc#12]
When running this script and playing videos through VLC, the script is always assuming that the playback is always at normal speed, which is for the most part correct, but if I'm doing something a bit less interesting, I may want to change the playback speed to speed it up, or slow the video down to analyse it, so I'd like the RPC to have the time remaining updated accordingly.

**Comment by Pigpog** [comment]
Thanks for the suggestion, I wouldn't have thought to add that! I'll be able to work on it Sunday at the earliest.

**Comment by Pigpog** [comment]
Feature added in 5d67381
Thanks
