### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by DePianoman** [Pigpog/vlc-discord-rpc#13]
**Describe the bug**
Running rpc.js after following instructions yields the error shown in **Terminal output**

**To Reproduce**
1. Install and follow instructions
2. Error

**Terminal output**

    PATH\node_modules\discord-rich-presence\node_modules\discord-rpc\src\Client.js:128
        async login(options = {}) {
              ^^^^^

    SyntaxError: Unexpected identifier
        at Object.exports.runInThisContect (vm.js:76:16)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
    .
    .
    .

**Your Setup:**
 - OS: Windows
 - NodeJS version: v6.9.4

**Additional context**
N/A

**Comment by Pigpog** [comment]
Tested solution: Update node to at least version 8.11.4, preferably the latest version.
