### ISSUE TITLE
How do I uninstall this?

### ISSUE THREAD

**Issue by dfg555** [Pigpog/vlc-discord-rpc#15]
Might be a stupid question but do I just uninstall node and git? And also delete the "vlc-discord-rpc-master" folder?

**Comment by Pigpog** [comment]
On what operating system?

**Comment by dfg555** [comment]
Windows 10

**Comment by Pigpog** [comment]
Oh, sorry, i read your question as "how do i" instead of "do i". Yeah, you can just do the normal procedure for uninstalling node and git, and delete that folder.
