### ISSUE TITLE
NPM Error and Discord displaying wrong info.

### ISSUE THREAD

**Issue by LukeMageSlayerYT** [Pigpog/vlc-discord-rpc#16]
**Describe the bug**
Its giving me loads of errors when i try to install npm and the rpc isnt working correctly.
`npm audit fix` doesnt fix the problem. Ive tried to run with and without Admin.

Does the script show an error? 
Check terminal output.

Does Discord display that you are "Playing VLC Media Player"? 
Yes but its broken. https://i.imgur.com/QlOYi6R.png

**To Reproduce**
It happens everytime i try to install it.

**Terminal output**
Your environment has been set up for using Node.js 11.6.0 (x64) and npm.

C:\Windows\System32>cd "C:\Users\Luke\Downloads\vlc-discord-rpc-master"

C:\Users\Luke\Downloads\vlc-discord-rpc-master>npm install
npm WARN discord-rpc@3.0.1 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN discord-rpc@3.0.0 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

audited 53 packages in 1.458s
found 11 vulnerabilities (9 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Luke\Downloads\vlc-discord-rpc-master>

**Your Setup:**
 - OS: Windows 10 Pro 
 - NodeJS version v11.6.0 

**Additional context**

**Comment by Pigpog** [comment]
When you run `npm install` it is giving you _warnings_ that there are packages you _could_ get but are not needed for this project. The output you posted is ideal.
To address the other concern about it displaying the wrong information, what steps have you taken to get it working? Remember: You must change the settings listed in the readme and also change config.js to match. And dont forget to restart VLC afterward.

**Comment by krampfcookie** [comment]
I helped him setting it up and told him to delete the issue after we got it working. So you can close the issue.
