### ISSUE TITLE
Displaying "Now Playing" for Radio Streams.

### ISSUE THREAD

**Issue by krampfcookie** [Pigpog/vlc-discord-rpc#17]
If its possible, could you add a function, that instead of trying to display artist and album for radio streams, it shows the "Now Playing" information instead?
![image](https://user-images.githubusercontent.com/46372994/50722975-9aa49080-10d7-11e9-8670-82e5cdc30610.png)

![image](https://user-images.githubusercontent.com/46372994/50722965-7ea0ef00-10d7-11e9-922a-9a75bd4e1531.png)

**Comment by Pigpog** [comment]
This feature has been implemented!
Please see commit https://github.com/Pigpog/vlc-discord-rpc/commit/f894c51db8a44469da101f1f11ba5f3efc159d03
