### ISSUE TITLE
Discord displays wrong info

### ISSUE THREAD

**Issue by GamexDani** [Pigpog/vlc-discord-rpc#19]
**Describe the bug**
I did everything as it says in the readme file but on discord it just says "Nothing is playing", I have tried with multiple audio files and none of them will show as if they were playing (https://i.imgur.com/E4zIZWw.png)

**To Reproduce**
I did all the necessary steps, let me pull up pretty much all the config files: https://i.imgur.com/KY2CI6q.png https://i.imgur.com/0CyaRNu.png & https://i.imgur.com/7N8tlCx.png

**Terminal output**
https://i.imgur.com/0CyaRNu.png I have also tried with cmd and PowerShell

**Your Setup:**
 - OS: Windows
 - NodeJS version v11.6.0

**Comment by Pigpog** [comment]
Does the command `git` work in that same cmd prompt?

**Comment by shikhir-arora** [comment]
I would also confirm that the VLC local web server/player is running (https://github.com/Pigpog/vlc-discord-rpc#setup) -- if it is, you should be able to go to `http://127.0.0.1:8080` and be prompted for a password/see the web player. If it cannot connect, then that may be an indicator of something not working on your end.

**Comment by GamexDani** [comment]
> 
> 
> Does the command `git` work in that same cmd prompt?

yes



> 
> 
> I would also confirm that the VLC local web server/player is running (https://github.com/Pigpog/vlc-discord-rpc#setup) -- if it is, you should be able to go to `http://127.0.0.1:8080` and be prompted for a password/see the web player. If it cannot connect, then that may be an indicator of something not working on your end.

And nope, any idea on how to fix that?

**Comment by Pigpog** [comment]
> And nope, any idea on how to fix that?
Does your main interfaces tab look like [this?](http://0x0.st/zKUM.png)

**Comment by GamexDani** [comment]
> 
> 
> > And nope, any idea on how to fix that?
> 
> Does your main interfaces tab look like [this?](http://0x0.st/zKUM.png)

I just fixed it, I'm just really retarded and forgot to change that parameter when I changed my hard drive, sorry for any inconveniences

**Comment by Pigpog** [comment]
no problem
