### ISSUE TITLE
Special characters in passwords

### ISSUE THREAD

**Issue by FogLizard** [Pigpog/vlc-discord-rpc#20]
When I add VLC process as a game, Discord grabs the current band name and song title playing and then never updates it upon songs changing or vlc restarting.

I've removed the username below, don't mind the double slashes

node /home/<username>/vlc-discord-rpc/rpc.js withvlc
Running...
url.js:338
      this.auth = decodeURIComponent(rest.slice(0, atSign));
                  ^

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:338:19)
    at Object.urlParse [as parse] (url.js:149:13)
    at Request.init (/home/<username>/vlc-discord-rpc/node_modules/request/request.js:138:53)
    at new Request (/home/<username>/vlc-discord-rpc/node_modules/request/request.js:98:8)
    at request (/home/<username>/vlc-discord-rpc/node_modules/request/index.js:50:11)
    at VlcService.HttpService.get (/home/<username>/vlc-discord-rpc/node_modules/droopy-http/HttpService.js:18:3)
    at VlcService._statusRequest (/home/<username>/vlc-discord-rpc/node_modules/droopy-vlc/VlcService.js:27:7)
    at VlcService.status (/home/<username>/vlc-discord-rpc/node_modules/droopy-vlc/VlcService.js:49:14)
    at update (/home/<username>/vlc-discord-rpc/rpc.js:28:6)

Linux
node --version v11.14.0

There were 11 vulnerabilities and audit couldn't fix it, so I installed with no audit.

**Comment by Pigpog** [comment]
Do not add the vlc process to your Game Activity list.
Please reply with lines 2 and 3 of your config.js file

**Comment by FogLizard** [comment]
Here's the config, I've only changed the pass and it was formatted like that originally after I git cloned.
I've been adding VLC manually because it is not showing up on it's own.

exports.vlcPass="the_password_ive_set"    //Lua HTTP password^M
exports.vlcPort=8080            //default value^M
exports.vlcHost="localhost"     //shouldnt need to change but whatever^M
//Start commands^M
exports.windowsvlc=`C:/Program Files/VideoLAN/VLC/vlc.exe`^M
exports.linuxvlc=`vlc`^M
exports.macvlc=`/Applications/VLC.app/Contents/MacOS/VLC`^M

**Comment by Pigpog** [comment]
> I've been adding VLC manually because it is not showing up on it's own.

Then what youre seeing isn't the rich presence, and the rich presence isn't work at all.
>There were 11 vulnerabilities and audit couldn't fix it, so I installed with no audit.

I have updated the package.json file, solving all of the vulnerabilities. Please clone the repository again.

**Comment by FogLizard** [comment]
I've re-cloned and re-installed without any warnings, but it's still not working with the same output in bash as in OP. I can add vlc manually with correct title only if I start it with

node /home/user/vlc-discord-rpc/rpc.js withvlc

But it still won't update the title. I've enabled development mode and still no luck.

**Comment by Pigpog** [comment]
I was able to replicate the problem. If your password contains special characters, you're probably creating unicode sequences that aren't allowed in the uri schema.

**Comment by FogLizard** [comment]
I've removed the special chars and now it's working, thank you for your help!
Is there a way to customize the text it's sending to Discord? It shows the "VLC Media Player" text near the nickname first instead of the band name and song title.

**Comment by Pigpog** [comment]
> Is there a way to customize the text it's sending to Discord?

Unfortunately, that is beyond the realm of possibility with rich presence at this time. Even Spotify doesn't have that.

I'm gonna leave this issue open until I implement either a warning or a filter for the password.

**Comment by FogLizard** [comment]
Np, I am still happy it's working as intended. You're doing an awesome job, thanks again! Please let me know here if I can be helpful testing stuff for you until the bug is fixed.

**Comment by dylhack** [comment]
Thank you, @FogLizard [I have patched this bug](https://github.com/dylhack/vlc.js/commit/01a1c27f7a7e753de361ccc29d4030c048de5300) on my HTTP wrapper make sure you use VLC.js 1.1.0 and above to allow symbols in the login process.
