### ISSUE TITLE
EXE file is a virus?

### ISSUE THREAD

**Issue by ohlookitsderpy** [Pigpog/vlc-discord-rpc#25]
Just downloaded the latest version to find Windows Defender screaming that it found threats. Here's the info: 
<img src='https://u.derpyenterprises.org/746845.png'>

**Comment by dylhack** [comment]
The "[start.exe](https://github.com/Pigpog/vlc-discord-rpc/blob/master/start.exe)" is a compiled version of "[start.bat](https://github.com/Pigpog/vlc-discord-rpc/blob/master/start.bat)" you can review and run the code for yourself.

**Comment by CNSabata** [comment]
I have issued a formal report to the Github moderation team. Your EXE on the last release (v2.2.3) is flagged on 33 engines in VirusTotal.
https://www.virustotal.com/gui/file/575988d0665d7118b405d944a252570a9e7d7c4b3980871e815df29b10d352b0/detection
![image](https://user-images.githubusercontent.com/20067074/59819144-f5007900-9326-11e9-9767-35d8ba569838.png)

**Comment by dylhack** [comment]
As of commit cd585e2, start.exe won't ship with any new versions of vlc-discord-rpc.
