### ISSUE TITLE
Readme could use additional information

### ISSUE THREAD

**Issue by Cknight70** [Pigpog/vlc-discord-rpc#28]
As the readme currently is, I am really not sure what how this discord rich presence is supposed to work. I think adding some clarification or more details may help people in the same situation as I am.

I am running Linux, my vlc is installed in the default location /usr/bin/vlc
I also installed npm into the unzipped folder to be safe.
This is what happens when I run the script. 
![image](https://user-images.githubusercontent.com/28763729/61614120-320aa480-ac20-11e9-8255-6f315401eefa.png)

**Comment by Cknight70** [comment]
This may actually be an error.
I tried running it detached (`npm start detached`) with the following error:

`(node:18738) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9090
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
(node:18738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Happy to provide more information.

**Comment by Cknight70** [comment]
I have figured out the problem. vlc must be closed at the time the script was run so that the script can open VLC. I think some clarification may help in the readme. Thank you.

**Comment by virivongithub** [comment]
im working on the new readme for pigpog

**Comment by dylhack** [comment]
Readme is better in 3.0.0, here's a preview / working version! https://github.com/dylhack/vlc-discord-rpc/tree/extras-ts#vlc-discord-rpc
