### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not connect

### ISSUE THREAD

**Issue by SupperCraft5000** [Pigpog/vlc-discord-rpc#29]
**Describe the bug**
The script start the vlc right but don´t display any information in Discord.

**To Reproduce**
1. Click on 'start.bat'
2. Wait 1-2 sec.
3. Boom Error

**Terminal output**
https://pic.shadowgaming.de/upload/1550833548.png

**Your Setup:**
 - OS: https://pic.shadowgaming.de/upload/505386567.png
 - https://pic.shadowgaming.de/upload/1911386343.png

**Additional context**

**Comment by Pigpog** [comment]
This error message means that the discord-rpc module failed to connect to your discord client. This has been reported before and I don't know what causes it, but here are some things to make sure of:

- You are using the discord desktop client
- You have "Display currently running game as a status message" turned on in discord
- Your discord desktop client isn't being run with administrator privileges (you'd know if it was)

**Comment by SupperCraft5000** [comment]
I have found the error don´t run Discord as a Admin
