### ISSUE TITLE
Errors when trying to install

### ISSUE THREAD

**Issue by kaosjr** [Pigpog/vlc-discord-rpc#3]
I get this message when I try to install it:

D:\Downloads\vlc-discord-rpc-master>npm install
npm WARN discord-rpc@3.0.0-beta.9 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 2.502s

D:\Downloads\vlc-discord-rpc-master>

I can't seem to install any of the peer dependencies required; register-scheme and erlpack install but the error doesn't go away, and sodium doesn't install at all, with really strange errors.

When I try launching the program without these dependencies, it just outputs a message about N-API and hangs.

**Comment by Pigpog** [comment]
From what you tell me it seems the program actually runs fine. Give it a second to check VLC

**Comment by kaosjr** [comment]
I'm using the latest version of VLC, 3.0.1, because I updated to see if that would make a difference.

**Comment by Pigpog** [comment]
have you tried letting the program sit for a little? theres no immediate output and it takes about 4 seconds to output anything if VLC is running.

**Comment by kaosjr** [comment]
I let it sit for around 2 minutes, no dice.

**Comment by Pigpog** [comment]
Did you configure VLC and the config,js file properly?

**Comment by kaosjr** [comment]
Huh, it randomly is now working fine.
Literally changed nothing, but it's working now.

**Comment by Pigpog** [comment]
glad you could figure it out.
