### ISSUE TITLE
Launch in detached mode without VLC open give an error

### ISSUE THREAD

**Issue by TheWWorld** [Pigpog/vlc-discord-rpc#30]
Hi,

I've tried to start the RPC when my windows session open, but if VLC is not started i get an error

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vlc-discord-rpc@2.2.0 start: `node ./src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vlc-discord-rpc@2.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I hope that will be fixed soon, thank you :)

**Comment by dylhack** [comment]
I'll work on a prettier error on our next release which will fix many bugs and make the UX a lot smoother.

**Comment by dylhack** [comment]
Here's a preview release of the next version. Hope you like it so far.
https://github.com/dylhack/vlc-discord-rpc/releases/tag/3.0.0

**Comment by TheWWorld** [comment]
> 
> 
> Here's a preview release of the next version. Hope you like it so far. It handles the error you're looking at rather than that nonsense it says "Failed to connect to VLC, is it open?" until it is open.
> https://github.com/dylhack/vlc-discord-rpc/releases/tag/3.0.0

Works fine now, thank you my dude ♥
