### ISSUE TITLE
when i open the script and play some video in to vlc it doesnt show on discord

### ISSUE THREAD

**Issue by ViktorMYT** [Pigpog/vlc-discord-rpc#32]
this is the log
https://paste.gg/p/anonymous/7de6030369b34ec6bb43985a2d50b61d/files/4f7352d4c7574fbe8fb14350f6971913/raw

i use busenlabs linux debian 9

**Comment by Pigpog** [comment]
Try renaming the video file to a name shorter than 128 characters.

**Comment by ViktorMYT** [comment]
Hi, I sloved the issue problem was that i tried to play MKV X265 video I used video encoder FFmpeg to convert it to MP4 X264 and now it works could you please add mkv x265 support because many of new videos are in that format.
