### ISSUE TITLE
RPC staying active when VLC is closed (detached mode)

### ISSUE THREAD

**Issue by GreasyGarlic** [Pigpog/vlc-discord-rpc#33]
While running in detached mode if the user decides to quit VLC while still running this program the RPC continues to show up on the user's profile.

**Comment by dylhack** [comment]
The rich presence will clear once it reaches the "sleep time" this can be set in the [config.json](https://github.com/Pigpog/vlc-discord-rpc/blob/master/config/config.js#L17), by default it's 30 seconds until cleared.
