### ISSUE TITLE
RPC staying active when VLC is closed (detached mode), even though 30 seconds mark has passed

### ISSUE THREAD

**Issue by Katoru** [Pigpog/vlc-discord-rpc#37]
Hello,

I have the same problem as described in this issue.

https://github.com/Pigpog/vlc-discord-rpc/issues/33

If i ever close VLC, Discord still display whatever i was listening to. Even after the 30 seconds mark. I tried to edit it to 4000. It still displays it forever. Once it reaches "0 seconds remaining".

It stays like that :
![image](https://user-images.githubusercontent.com/26099340/80917352-95ecfc80-8d5e-11ea-9f40-5e1116c5ebe3.png)

The only way to make it disapear at all, is to close the CMD window where vlc-discord-rpc start.bat was launched

Thank you for this plugin

**Comment by Pigpog** [comment]
Thank you for bringing this to my attention. I hope this commit fixes the problem you are encountering.
