### ISSUE TITLE
Doesn't work when pinned to the start bar or in a dock.

### ISSUE THREAD

**Issue by sqorpeus** [Pigpog/vlc-discord-rpc#38]
**Describe the bug**
Doesn't work when pinned to the start bar or in a dock.
Says NPM isn't installed when it is and that VLC player isn't working.
Does Discord display that you are "Playing VLC Media Player"?  Only when I start the bat file in the directory it's saved in.

**To Reproduce**
1. Go to '...' Pinned bat file or Shelf item on Nexus Dock.
2. Click on '....' Pinned bat file or Shelf item on Nexus Dock.
3. Scroll down to '....' No scrolling necessary

**Terminal output**
A problem occurred while launching vlc.
Press any key to continue...

**Your Setup:**
 - OS: [Windows 7 Pro]
 - NodeJS version 12.16.3-x64

**Additional context**

**Comment by Pigpog** [comment]
Did you set the "Start In" property of the shortcut to the directory of vlc-discord-rpc?

**Comment by sqorpeus** [comment]
Yes.

**Comment by Pigpog** [comment]
Does it work for you when it _isn't_ pinned to the start bar or in a dock? The "launching vlc" issue is indicative of an incorrectly set path to vlc in config.js. Most cases of it we're solved in 0915b68dbc7e7536961f68217ad6cfc73541fb73, so try the latest release.
