### ISSUE TITLE
Pull rich presence data off of Discord once VLC is closed?

### ISSUE THREAD

**Issue by WCBROW01** [Pigpog/vlc-discord-rpc#4]
I noticed that the VLC media player status stays after VLC is closed until you close the program. I want to keep this open in the background as a startup program, so I really need this behavior. Is this possible?

**Comment by Pigpog** [comment]
I've considered making the script start vlc for you and stop when vlc is closed. In fact, droopy-vlc has the code for this. Ill implement it soon.
Hopefully this is equivalent or better than what you are trying to accomplish.

**Comment by WCBROW01** [comment]
I kind of want it to start and stop on it's own without any user interaction, so yeah, something like that I guess.

**Comment by Pigpog** [comment]
New update should accomplish this.

[docs](https://github.com/Pigpog/vlc-discord-rpc/blob/master/README.md#to-make-all-in-one-shortcut-new-update)

[commit](https://github.com/Pigpog/vlc-discord-rpc/commit/c9cbb3daaefe77d66a37abd46ec97072ad5fd863)

I know this still doesn't help if you start vlc by opening a media file, but it's definitely an improvement.
