### ISSUE TITLE
If I close VLC while playing it still running in discord

### ISSUE THREAD

**Issue by JakubSladek** [Pigpog/vlc-discord-rpc#40]
**Describe the bug**
If I close VLC while playing any media it is still showing up in Discord, using detached mode.

**To Reproduce**
1. Play media on VLC
2. Start script
3. Close VLC
4. Discord still showing that media is playing

**Terminal output**
`0|app     |  Error: connect ECONNREFUSED 127.0.0.1:8080
0|app      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
0|app      |   errno: 'ECONNREFUSED',
0|app      |   code: 'ECONNREFUSED',
0|app      |   syscall: 'connect',
0|app      |   address: '127.0.0.1',
0|app      |   port: 8080
0|app      | }`

**Your Setup:**
 - OS: Windows 10
 - NodeJS version v12.13.0

**Additional context**
I temporary fixed it by editing error handler on diff.js and now working fine :)
I love this feature and I'm looking forward for the VLC Extension, good work, keep it up👍

**Code changed**:
**diff.js, line 57:**
`    .catch((err) => {
      last.state = "stopped";
      callback(last, false);
    });`

**Comment by Pigpog** [comment]
This was fixed in https://github.com/Pigpog/vlc-discord-rpc/commit/29a4132b7cb6b6a71eb1c48e3d58e4f7cc24bf89, but the release hasn't been put up yet. Sorry for the trouble
