### ISSUE TITLE
Open the bat file automatically when a file is played in VLC (detached mode)

### ISSUE THREAD

**Issue by TheFirstMe** [Pigpog/vlc-discord-rpc#41]
Is it possible to start the script when VLC is opened automatically? I don't want to start the script manually each time.

**Comment by ketjow384** [comment]
In linux I have the same problem, it cannot work after adding it to startup, only works when start it manually.
Please make it able to launch at startup and working.

**Comment by virivongithub** [comment]
just make a systemd module

**Comment by Pigpog** [comment]
or some kind of scheduled task, or modify your vlc shortcut, or make it run on startup in the background at all times in detached mode
