### ISSUE TITLE
Unable to get script working in 'detached' mode.

### ISSUE THREAD

**Issue by NovaLynxie** [Pigpog/vlc-discord-rpc#43]
**Describe the bug**
When loading the script, it installs correctly. Yet when trying to run 'detached' mode it simply won't detect VLC even if reopened.
Does the script show an error?
The error message shown is: 'Failed to reach VLC. Is it open?'
Does Discord display that you are "Playing VLC Media Player"?
Only in 'default' mode. I have not been able to get it to work on 'detached' mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to where you extracted the zipped contents to.
2. Modify the bat file to run in detached mode. Click on start.bat
3. Make sure VLC is open in the background while the script attempts to load up.
4. The error shows up in the batch file's console window.

**Terminal output**
Share what your terminal says when you run the script.
![image](https://user-images.githubusercontent.com/21307676/96022874-74358c80-0e49-11eb-994a-4c799b9f1c05.png)

**Your Setup:**
 - OS: Windows 10 Home
 - NodeJS version v12.18.4

**Additional context**
I have followed the instructions on how to configure for detached mode but still does not seem to work correctly, only works in default mode which isn't practical if I close the VLC window since the script also closes.

**Comment by Pigpog** [comment]
To confirm, you have:
 - Set the port in config.js to 8080
 - Enabled the web interface in VLC and set a password for it
 - Included the password in config.js

right?

**Comment by NovaLynxie** [comment]
Ah... haven't done that yet. Had another look at the github and found the information needed to get it working.
Its now been set, I'll put the password into the config.js now.

**Comment by NovaLynxie** [comment]
There we go, it's working now. I'll make sure to check next time. Thanks for the help 😄

**Comment by Pigpog** [comment]
no problem, I definitely need to make it more clear (and easier) to use this project
