### ISSUE TITLE
node_modules not found

### ISSUE THREAD

**Issue by Realswitzer** [Pigpog/vlc-discord-rpc#44]
**Describe the bug**

After double clicking start.bat, it can't find the node_modules folder. After attempting to install the modules, it errors out with: "A problem occurred while installing modules. Ensure that npm is installed."
I have node and npm installed to C:\node\nodejs and also have the path added to the %PATH% environmental variable.

**To Reproduce**
1. Extract the newest version (Sept 6 - Version 2.2.7) (extracted to C:\Users\user\Desktop)
2. Install the 15.2.0 node binaries, extract (extracted to C:\node)
3. Add the binaries to the path variable.
4. Launch start.bat

**Terminal output**
Share what your terminal says when you run the script.

Did not detect node_modules directory; Installing modules.
[Attempted installing modules, too quick to read, after 2-5 modules gives below output.]
A problem occurred while installing modules. Ensure that npm is installed.
Press any key to continue . . .

**Your Setup:**
 - OS: Windows 8.1 Enterprise
 - NodeJS version v15.2.0, NPM version v7.0.8

**Additional context**

**Comment by Pigpog** [comment]
You can get the full output by running start.bat from an existing command prompt window

**Comment by Realswitzer** [comment]
Sorry for the late reply on this, running from an existing command prompt closed command prompt and gave the output. I have screen recorded this and analyzed frame by frame.
------
Did not detect node_modules; Installing modules...
[..........] idealTree:vlc-discord-rpc: sill idealTree buildDeps
[..........] idealTree:vlc.js: sill fetch manifest ws@^7.3.1
A problem occurred while installing modules. Ensure that npm is installed.
Press any key to continue . . .
------
Hopefully this helps any.

**Comment by Pigpog** [comment]
That's very strange. I can tell NPM is installed and can be reached. Make sure you're not running it as administrator, and maybe try the new bundle release that comes with node.

**Comment by Realswitzer** [comment]
Closing, old issue and could not fix the issue. Switched to *nix so not applicable anymore for me.
