### ISSUE TITLE
Christmas Logo!

### ISSUE THREAD

**Issue by TheAndroidx1** [Pigpog/vlc-discord-rpc#47]
Not to seem pushy or anything, but I think it would be nice to change the logo in the status to the Christmas logo so that it matches the logo in the application, I think that would be a neat feature!

**Comment by Pigpog** [comment]
I have an even cooler way to solve this problem, Ill add that in a future commit and mention this issue. thanks for reminding me to add this

**Comment by Pigpog** [comment]
ok now you can change your icon by changing the largeIcon parameter in config.js to "vlcxmas". close this issue if this solves your problem

**Comment by TheAndroidx1** [comment]
Thanks for that!
First time having a dev respond to me, pretty cool :D
