### ISSUE TITLE
Errors while installing

### ISSUE THREAD

**Issue by Mehvix** [Pigpog/vlc-discord-rpc#5]
Whenever I attempt to install I get 

> C:\Users\maxla\Desktop\vlc-discord-rpc-master>npm install
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.0 but none is installed. You must install peer dependencies yourself.

> added 39 packages from 56 contributors and audited 46 packages in 10.77s
found 11 vulnerabilities (9 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Pigpog** [comment]
Those are just warnings and can be ignored.
