### ISSUE TITLE
Connecting to Discord... Failed to connect to Discord. 

### ISSUE THREAD

**Issue by BaseCrunch** [Pigpog/vlc-discord-rpc#50]
Starting script...

> vlc-discord-rpc@2.2.12 start C:\Users\bweak\Desktop\vlc-discord-rpc-win64-bundle\vlc-discord-rpc
> node ./src/app.js

Connecting to Discord...
Failed to connect to Discord. Is your Discord client open? Retrying in 20 seconds...

**Comment by Pigpog** [comment]
200

**Comment by BaseCrunch** [comment]
?

**Comment by Pigpog** [comment]
Restart Discord and try again. If that doesn't work, try restarting your computer. Do not run the start script or Discord with elevated permissions. Be sure you are using the Discord desktop client and not the website.

**Comment by BaseCrunch** [comment]
Installed Discord Canary and restarting my pc worked thank you so much!
