### ISSUE TITLE
Invalid or unexpected Token

### ISSUE THREAD

**Issue by byzocker** [Pigpog/vlc-discord-rpc#52]
**Describe the bug**
Does the script show an error? yes
Does Discord display that you are "Playing VLC Media Player"? no

**To Reproduce**
1. Open the "start.bat" file

**Terminal output**
with v12.18.3
![image](https://user-images.githubusercontent.com/59401089/115345201-b94aca80-a1ae-11eb-97f1-8e2366dc3738.png)
with v15.14.0
![image](https://user-images.githubusercontent.com/59401089/115346378-640fb880-a1b0-11eb-9bf2-d123192976ec.png)

**Your Setup:**
 - OS: [Windows 10 version 20H2 Build 19042.928]
 - NodeJS version (v12.18.3 i also updated to v15.14.0)

**Additional context**
I have installed VLC in the Program Files of my 2nd hard drive, I have added the path to the config.js

**Comment by Pigpog** [comment]
The error message is in fact pointing at the issue. In config.js, theres a quotation mark (") on the password line that shouldn't be there (its an unexpected token). That line should just be `password: '',`

**Comment by byzocker** [comment]
that worked thank you
