### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by LightyCat** [Pigpog/vlc-discord-rpc#59]
When i start the start.bat it says Did not detect node_modules directory; Installing Modules
and when it does the other thing it gives me A Problem occured white installing modules. Ensure that npm is installed
but i have Node.js/npm
![image](https://user-images.githubusercontent.com/91459350/140485690-d7a82e0d-a945-4bf5-b29c-e9df17117ad8.png)

**Comment by LightyCat** [comment]
Also i used version 2.2.0 now and it works but you have to fix this error

**Comment by Pigpog** [comment]
That error message comes from start.bat. The only thing that changed about start.bat between those two releases is how it displays error messages. This minor change has actually been undone in recent releases.
Please try using the latest release and be sure to extract the zip file to a folder your user can write in. Do not run anything as administrator.

**Comment by LightyCat** [comment]
> That error message comes from start.bat. The only thing that changed about start.bat between those two releases is how it displays error messages. This minor change has actually been undone in recent releases. Please try using the latest release and be sure to extract the zip file to a folder your user can write in. Do not run anything as administrator.

Now i changed the folder it was in but this time it gave me some big errors i think its because i dont have python cause it said "Could not find python" but when i run it again it gave me "A Problem occured white installing modules. Ensure that npm is installed" again

**Comment by LightyCat** [comment]
Heres the erro

https://user-images.githubusercontent.com/91459350/140552289-d65e016a-b691-45bc-9e5e-765b83c13307.mp4

**Comment by Pigpog** [comment]
Interesting, that video helps a lot, thanks. It attempts to install the node modules and then fails.

I just tried deleting my node_modules folder and it actually fails for me too! NPM refuses to run because i need to update npm using the command `npm install -g npm@8.1.3`. Try updating to the latest npm

**Comment by LightyCat** [comment]
> Interesting, that video helps a lot, thanks. It attempts to install the node modules and then fails.
> 
> I just tried deleting my node_modules folder and it actually fails for me too! NPM refuses to run because i need to update npm using the command `npm install -g npm@8.1.3`. Try updating to the latest npm

I did what you said but Still the same error..
I even unistalled Node.Js and installed the 17.0.1 version again

**Comment by LightyCat** [comment]
and when i do that command it shows this
![image](https://user-images.githubusercontent.com/91459350/140562151-8e4c598a-dbab-4fb1-bcbd-860e96e6d2da.png)

**Comment by Pigpog** [comment]
Looks like it successfully updated npm. Now try running start.bat again

**Comment by LightyCat** [comment]
> Looks like it successfully updated npm. Now try running start.bat again

Didnt work..

**Comment by Pigpog** [comment]
could you try using command prompt to install the modules? `cd` into the vlc-discord-rpc directory and run `npm i`. see what error message appears. Alternatively, use the latest commit (not release) because it leaves npm error messages visible

**Comment by LightyCat** [comment]
https://user-images.githubusercontent.com/91459350/140566444-e861e647-d57f-4c42-83d7-4a4cc81facc6.mp4

**Comment by LightyCat** [comment]
> could you try using command prompt to install the modules? `cd` into the vlc-discord-rpc directory and run `npm i`. see what error message appears. Alternatively, use the latest commit (not release) because it leaves npm error messages visible

sorry it was the wrong command

**Comment by Pigpog** [comment]
I think at this point you should uninstall and reinstall nodejs/npm, because it looks like npm is borked

**Comment by LightyCat** [comment]
> I think at this point you should uninstall and reinstall nodejs/npm, because it looks like npm is borked

can you give me the download link i think i installed the wrong one

**Comment by Pigpog** [comment]
https://nodejs.org/dist/v16.13.0/node-v16.13.0-x64.msi
you probably want this, the windows 64 bit installer

**Comment by LightyCat** [comment]
> https://nodejs.org/dist/v16.13.0/node-v16.13.0-x64.msi you probably want this, the windows 64 bit installer

yea cause this one is 16.13.0 and i was using 17.0.1

**Comment by Pigpog** [comment]
honestly i dont think the version matters much, though I havent tested 17

**Comment by LightyCat** [comment]
> honestly i dont think the version matters much, though I havent tested 17

ummmm how do i uninstall npm cause i uninstalled node.js and installed the link you gave me and the same error
![image](https://user-images.githubusercontent.com/91459350/140567636-845fe0e6-8805-40c6-8027-431a8926e27e.png)

**Comment by Pigpog** [comment]
using the add/remove programs thing of windows

**Comment by LightyCat** [comment]
> using the add/remove programs thing of windows

Still didnt get fixed

**Comment by Pigpog** [comment]
have you tried the latest bundle release of vlc-discord-rpc? it should work no matter what. if not, ill be back in at least 6 hours

**Comment by LightyCat** [comment]
> have you tried the latest bundle release of vlc-discord-rpc? it should work no matter what. if not, ill be back in at least 6 hours

wheres the link

**Comment by Pigpog** [comment]
https://github.com/Pigpog/vlc-discord-rpc/releases/download/2.3/vlc-discord-rpc-win64-bundle.zip

**Comment by LightyCat** [comment]
> https://github.com/Pigpog/vlc-discord-rpc/releases/download/2.3/vlc-discord-rpc-win64-bundle.zip

Why does the bundle wants npm

**Comment by LightyCat** [comment]
> https://github.com/Pigpog/vlc-discord-rpc/releases/download/2.3/vlc-discord-rpc-win64-bundle.zip

Its now fixed Tnx!
