### ISSUE TITLE
Error when 'linux' is defined in the platformDefault const

### ISSUE THREAD

**Issue by ItsGarek** [Pigpog/vlc-discord-rpc#61]
![image](https://user-images.githubusercontent.com/52253795/144760745-839bfe12-bf4b-4460-8d9f-ba3dee4266ca.png)
Removing linux from the const seems to fix the issue.

**Comment by Pigpog** [comment]
the error isn't about it attempting to run the linux path, it's about a parsing error for the line above it. you must have edited the path in app.js incorrectly. Perhaps you missed a comma after the Windows path? Or used an unescaped backslash (if using backslashes in the path, you MUST double them up (\\).

**Comment by ItsGarek** [comment]
You are right I updated the issue. My bad

**Comment by Pigpog** [comment]
You should be able to have the linux path defined, it just has to be formatted correctly. I can take a look at your modifications to identify what went wrong

**Comment by ItsGarek** [comment]
okay I got it, the comma wasn't there, but it worked when I used cmd.. I am stoopid -.-

**Comment by Pigpog** [comment]
glad you could get it working, have a good one
