### ISSUE TITLE
Change the default "Playing VLC Media Player" rich presence.

### ISSUE THREAD

**Issue by jeryjs** [Pigpog/vlc-discord-rpc#62]
I was just hoping that there would be some way to change the rich presence from "Playing VLC Media Player" to smth else for me like by changing the app ID r smth.
So, is it possible?

**Comment by Pigpog** [comment]
Yes, it is possible to change that text. Create a new Discord Application, name it what you want it to say, and then use that app ID. Be sure to upload the image assets to the rich presence section.

**Comment by jeryjs** [comment]
Thx, I was able to change the name, but I noticed that It doesn't show the paused icon when the video is paused. Is there anything I need to change here?
![image](https://user-images.githubusercontent.com/77010142/147197468-3a565141-59f9-4026-a027-5cb461388c5f.png)
![image](https://user-images.githubusercontent.com/77010142/147197544-65b26504-055e-45f7-9c72-f2f9a05ad103.png)

**Comment by Pigpog** [comment]
perhaps it should be "paused" instead of "pause"

**Comment by jeryjs** [comment]
Oh! Okay
tho in the /icons/ folder it was mentioned 'paused'

**Comment by jeryjs** [comment]
oh, sry, my bad... It was 'pause' and not 'paused'

**Comment by Pigpog** [comment]
aw cool lemme know if it works

**Comment by jeryjs** [comment]
Nope... no luck. It still doesn't show the paused icon

**Comment by Pigpog** [comment]
Try reopening discord, maybe the asset hasnt propagated to your client yet

**Comment by jeryjs** [comment]
Ah! I fixed it!
I had to set the 'small image key' to 'pauselight'

**Comment by jeryjs** [comment]
tho is it possible to make the playing/ paused icons white (like before) instead of black

**Comment by Pigpog** [comment]
youd have to name the light assets `playing` `paused` `stopped`, sorry thats a bit inconvenient to change now for ya

**Comment by jeryjs** [comment]
kay!
thx!
and hw do i change the vlc icon?
rn only the default 'vlc' icon works

**Comment by Pigpog** [comment]
the large icon can be set in config.js, the `largeIcon` setting

**Comment by jeryjs** [comment]
oh, sry, I meant how to add my own vlc icon instead of default

**Comment by Pigpog** [comment]
just upload a new large icon as an asset and set its name in config.js

**Comment by jeryjs** [comment]
any name?

**Comment by Pigpog** [comment]
any name works yes

**Comment by jeryjs** [comment]
will try now

**Comment by jeryjs** [comment]
Nope... didnt work
Now the Paused icon appears as the large icon and vlc icon is absent

**Comment by Pigpog** [comment]
try reloading discord

**Comment by jeryjs** [comment]
> youd have to name the light assets `playing` `paused` `stopped`, sorry thats a bit inconvenient to change now for ya

It's still black even though I removed all the black icons and replaced them with the light

**Comment by jeryjs** [comment]
> try reloading discord

ok

**Comment by Pigpog** [comment]
your browser is caching the assets in the application. it can take some time for changes to show up on your end. restarting your discord client usually makes it reload the assets

**Comment by jeryjs** [comment]
Yay~ Now the small icons appear in white.

Also, 
![image](https://user-images.githubusercontent.com/77010142/147200565-3a2df52f-37f3-4170-b72c-e142daa6e9e7.png)
Should I add the other images such as 'vlcflat', 'vlcblue', 'vlcneon', etc? cuz it doesnt work if i set anything other than 'vlc' in config.js

**Comment by Pigpog** [comment]
nah the other images arent required. not sure why names other than vlc wouldnt work, other than caching maybe

**Comment by jeryjs** [comment]
> Thx, I was able to change the name, but I noticed that It doesn't show the paused icon (or volume) when the video is paused. Is there anything I need to change here? But it displays the 'Playing' icon fine. ![image](https://user-images.githubusercontent.com/77010142/147197468-3a565141-59f9-4026-a027-5cb461388c5f.png) ![image](https://user-images.githubusercontent.com/77010142/147197544-65b26504-055e-45f7-9c72-f2f9a05ad103.png)

NOOOOO It started frm problem 1 again :(
It doesnt show the 'paused' icon even if I set the 'small image key' to 'pauselight' in developer portal

**Comment by Pigpog** [comment]
you know the developer portal doesnt change your actual rich presence right? it shouldnt be possible for the icon to not show up in the rich presence visualizer when you pick it-- unless theres a bug on discord's end

**Comment by jeryjs** [comment]
oh... didn't knw that lol
well, maybe waiting for a bit could fix it

**Comment by Pigpog** [comment]
most likely. the discord servers dont like to work very hard when it comes to caching that stuff

**Comment by jeryjs** [comment]
🤣 Yea seems like it.
Thx for helping me.

**Comment by Pigpog** [comment]
no problem, glad you could get it working, merry christmas
