### ISSUE TITLE
Rich Presence not removed when playback is paused (if sleepTime > updateInterval)

### ISSUE THREAD

**Issue by jeryjs** [Pigpog/vlc-discord-rpc#63]
As long as the 'sleepTime' value is equal to (or lesser than) the 'updateInterval' value, it works fine, but when I set the 'sleepTime' to even a slightly higher value, the rich presence isn't removed.

I want to be able to set the sleepTime to 60000 and the updateInterval to 3000, 
but even setting the sleepTime to 3500 and updateInterval to 3000, the rich presence doesn't remove.

![image](https://user-images.githubusercontent.com/77010142/147731077-7383cfdf-dbee-4d12-80dd-225d538838bd.png)

**Comment by Pigpog** [comment]
Thanks for pointing this out, I obviously didn't test that code very much after adding the `showStopped` option.
The commit I just put up should fix this, and I actually tested it this time, but maybe I should have you test it before I mark this closed.

**Comment by jeryjs** [comment]
Yay~!
It worked!
thx for fixing it :)

**Comment by Pigpog** [comment]
Good to hear! Ill make a few more fixes that ive been meaning to do and then make a new release. Happy new year.

**Comment by jeryjs** [comment]
Great!
Happy New Year!!
