### ISSUE TITLE
Script runs but not showing the VLC RPC in discord. Error SPAM in script.

### ISSUE THREAD

**Issue by krystlerc** [Pigpog/vlc-discord-rpc#67]
The image and title tells it.
The error spam as i run the script. The script is for win64 bundle. VLC shows up and play video, but doest show in discord any RPC or activity status.

![image](https://user-images.githubusercontent.com/21289418/152093713-a9385c44-63cc-41e8-8f44-195dd42a2bc2.png)

**Comment by Pigpog** [comment]
You have an http server running on port 8080, and thats the port that vlc's http interface uses. Change the port in config/config.js to something new.

**Comment by krystlerc** [comment]
Thanks, got it work.
