### ISSUE TITLE
i have a problem runnin vlc rpc

### ISSUE THREAD

**Issue by star67-d4c** [Pigpog/vlc-discord-rpc#68]
Did not detect node_modules directory; Installing modules...
A problem occurred while installing modules. Ensure that npm is installed.
![Problem NPM](https://user-images.githubusercontent.com/95832492/152659024-4e179418-586d-41d6-926e-93af3de467f4.png)

**Comment by star67-d4c** [comment]
btw it's already installed node js and npm / and the modules directory
![image](https://user-images.githubusercontent.com/95832492/152659142-0c1bd661-35c4-4870-be58-db092ecd99ca.png)

**Comment by Pigpog** [comment]
Do you usually install programs by extracting them to Program Files?

Doing anything in that folder requires administrator privileges. Extract the vlc-discord-rpc zip file to a folder that you actually have permissions for, and it will create a node-modules folder there.

**Comment by Pigpog** [comment]
Closing as this is not an issue with my program. You just need to extract it to somewhere inside your user directory (your Downloads folder for example) so it can properly run.
