### ISSUE TITLE
what did u expect this to say

### ISSUE THREAD

**Issue by Riperinono** [Pigpog/vlc-discord-rpc#7]
Hi, it seems to be working with me but I have this default message showing instead of the actually played file.
Do you know what I should check to fix this issue?
![image](https://user-images.githubusercontent.com/40810296/42249260-b04dfb86-7f2a-11e8-9b9b-5ad2e6871ab0.png)

**Comment by Pigpog** [comment]
Check if VLC is configured properly and matches the config file. To test it, try going to (http://localhost:8080/) and try logging in. If it doesnt prompt you for your login, VLC is configured wrong and not running the webserver, or it is running on a different port. If it logs in fine, check the password in the config file.

**Comment by Pigpog** [comment]
Did you get it working?

**Comment by Riperinono** [comment]
hey 
I'm sorry I didn't see your response to my issue, turns out that I already fixed the issue by myself, I did it by RE-checking the little square "web"  in the main interfaces menu of VLC and  `authorizing the connexion through my firewall`.
Thank u very much for your good work and the open-source initiative.
The shortcut is pretty handy as well.
