### ISSUE TITLE
Some album art are not showing, while others do.

### ISSUE THREAD

**Issue by taylorsalez** [Pigpog/vlc-discord-rpc#70]
I went and tagged every video file (around 77) with the title, album (which is the required one), and other tags.
I created a thumbnail for each video file, uploaded them all to the discord app.

I followed the instructions in ADVANCED.md.

The weird thing is, some do show an album art in the Discord rich presence, while others simply do not.

I have checked tags, codec, format, tag versions, file names, etc... there is no difference between a working mp4 file, and a non-working mp4 file. Same syntax, didn't forget the comas, proper spacing, etc...

Weirdly enough, every mkv file works (Matroska tags),, the inconsistency only happens with MP4 files.
![Matroska](https://user-images.githubusercontent.com/88684681/160285802-85172829-507f-4d37-a682-c1d02ce9b455.png)

MP4 file working correctly:
![mp4 working](https://user-images.githubusercontent.com/88684681/160285938-4c256c2d-1213-4f14-ae2b-37f8eacfcc5d.png)

MP4 file not working correctly:
![mp4 not working](https://user-images.githubusercontent.com/88684681/160286033-93e089f0-4842-40fe-acc9-f84e8eb2c7cd.png)

art.json file:
![Capture](https://user-images.githubusercontent.com/88684681/160286052-af0fae5b-16e6-44b8-8bb6-8377bc06bcef.PNG)

**Comment by taylorsalez** [comment]
Update: it seems some album art appear for half a second sometimes, then disappear.

**Comment by Pigpog** [comment]
Sorry for the months of silence. I just did some investigating, and i have a question. Are these downloaded YouTube videos?
I (coincidentally) tried to reproduce this with a downloaded YouTube video and found that my code recognizes it as a YouTube video using some metadata, and tries to show the YouTube large icon (which you probably don't have in your Application).

To fix this issue, then, you can either remove the "Youtube Start Time" metadata tag from each video, or delete lines [30 - 33 of format.js](https://github.com/Pigpog/vlc-discord-rpc/blob/master/src/rpc/format.js#L30).

I never anticipated the album art feature being used for videos, so I never tested that. But there's clearly no technical reason preventing this. A slight modification of the code would allow a TV show name to be used for the large image as well.

Hope this helps, sorry again for the delay, thanks for the challenge

**Comment by taylorsalez** [comment]
No worries about the delay!

Yeah, those are all Youtube videos I downloaded, cleared the metadata from, and re-tagged.
I ended up taking a day to convert every file to MKV, and only one file still did not work.

I turned line 30-33 into comment lines and it works now, thanks!

**Comment by Pigpog** [comment]
Awesome, glad I noticed that the YouTube metadata lingers in youtube-dl files, or i'd be so lost as to what the problem could be.
Have a good one!
