### ISSUE TITLE
Randomly crashing

### ISSUE THREAD

**Issue by flleeppyy** [Pigpog/vlc-discord-rpc#73]
**Describe the bug**
Script will randomly crash with an error

**To Reproduce**
1. Run start.bat
3. Mess around with the UI, it will eventually crash.

**Terminal output**
Share what your terminal says when you run the script.

![image](https://user-images.githubusercontent.com/18307183/178208935-314351f4-10b4-4f79-97d0-8d0f47a408ba.png)
```
Starting script...

> vlc-discord-rpc@2.2.12 start
> node ./src/app.js

Connecting to Discord...
Logged in as Flleeppyy
undefined:1
<html><body><h2>404 Not found</h2></body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new VLCStatus (C:\Program Files\VideoLAN\VLC\vlc-discord-rpc\node_modules\vlc.js\lib\src\http\classes\VLCStatus.js:13:27)
    at C:\Program Files\VideoLAN\VLC\vlc-discord-rpc\node_modules\vlc.js\lib\src\http\Requester.js:65:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Press any key to continue . . .
```

**Your Setup:**
 - OS: Windows 10 Pro
 - NodeJS: v16.9.1.

**Comment by Pigpog** [comment]
You have an HTTP server running on port 8080, which is the port that we need to access VLC on. 
If you intend on using attached mode, change the port number in config/config.js to any port >1024 thats not already in use (ie. 9090)
If you want to use detached mode, the easiest solution is to reconfigure the http server that's using 8080 to use another port.
